fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-json
        exclude: .devcontainer/
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys, --indent=4]
        exclude: .devcontainer/
      - id: check-yaml
      - id: end-of-file-fixer
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: no-commit-to-branch
        args: [-b, main]
