// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package api

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/Khan/genqlient/graphql"
	"github.com/massdriver-cloud/mass/pkg/api/scalars"
)

// Arguments required to get container repositories
type ContainerRepositoryInput struct {
	Location  string `json:"location"`
	ImageName string `json:"imageName"`
}

// GetLocation returns ContainerRepositoryInput.Location, and is useful for accessing the field via an interface.
func (v *ContainerRepositoryInput) GetLocation() string { return v.Location }

// GetImageName returns ContainerRepositoryInput.ImageName, and is useful for accessing the field via an interface.
func (v *ContainerRepositoryInput) GetImageName() string { return v.ImageName }

type Credential struct {
	ArtifactDefinitionType string `json:"artifactDefinitionType"`
	ArtifactId             string `json:"artifactId"`
}

// GetArtifactDefinitionType returns Credential.ArtifactDefinitionType, and is useful for accessing the field via an interface.
func (v *Credential) GetArtifactDefinitionType() string { return v.ArtifactDefinitionType }

// GetArtifactId returns Credential.ArtifactId, and is useful for accessing the field via an interface.
func (v *Credential) GetArtifactId() string { return v.ArtifactId }

// MutationValidationError includes the requested fields of the GraphQL type ValidationMessage.
// The GraphQL type's documentation follows.
//
// Validation messages are returned when mutation input does not meet the requirements.
// While client-side validation is highly recommended to provide the best User Experience,
// All inputs will always be validated server-side.
//
// Some examples of validations are:
//
// * Username must be at least 10 characters
// * Email field does not contain an email address
// * Birth Date is required
//
// While GraphQL has support for required values, mutation data fields are always
// set to optional in our API. This allows 'required field' messages
// to be returned in the same manner as other validations. The only exceptions
// are id fields, which may be required to perform updates or deletes.
type MutationValidationError struct {
	// A friendly error message, appropriate for display to the end user.
	//
	// The message is interpolated to include the appropriate variables.
	//
	// Example: `Username must be at least 10 characters`
	//
	// This message may change without notice, so we do not recommend you match against the text.
	// Instead, use the *code* field for matching.
	Message string `json:"message"`
}

// GetMessage returns MutationValidationError.Message, and is useful for accessing the field via an interface.
func (v *MutationValidationError) GetMessage() string { return v.Message }

type PreviewEnvironmentInput struct {
	Credentials           []Credential           `json:"credentials"`
	PackageConfigurations map[string]interface{} `json:"-"`
	// CI/CD event information (e.g.: GitHub Action Pull Request Event)
	CiContext map[string]interface{} `json:"-"`
}

// GetCredentials returns PreviewEnvironmentInput.Credentials, and is useful for accessing the field via an interface.
func (v *PreviewEnvironmentInput) GetCredentials() []Credential { return v.Credentials }

// GetPackageConfigurations returns PreviewEnvironmentInput.PackageConfigurations, and is useful for accessing the field via an interface.
func (v *PreviewEnvironmentInput) GetPackageConfigurations() map[string]interface{} {
	return v.PackageConfigurations
}

// GetCiContext returns PreviewEnvironmentInput.CiContext, and is useful for accessing the field via an interface.
func (v *PreviewEnvironmentInput) GetCiContext() map[string]interface{} { return v.CiContext }

func (v *PreviewEnvironmentInput) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*PreviewEnvironmentInput
		PackageConfigurations json.RawMessage `json:"packageConfigurations"`
		CiContext             json.RawMessage `json:"ciContext"`
		graphql.NoUnmarshalJSON
	}
	firstPass.PreviewEnvironmentInput = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.PackageConfigurations
		src := firstPass.PackageConfigurations
		if len(src) != 0 && string(src) != "null" {
			err = scalars.UnmarshalJSON(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal PreviewEnvironmentInput.PackageConfigurations: %w", err)
			}
		}
	}

	{
		dst := &v.CiContext
		src := firstPass.CiContext
		if len(src) != 0 && string(src) != "null" {
			err = scalars.UnmarshalJSON(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal PreviewEnvironmentInput.CiContext: %w", err)
			}
		}
	}
	return nil
}

type __premarshalPreviewEnvironmentInput struct {
	Credentials []Credential `json:"credentials"`

	PackageConfigurations json.RawMessage `json:"packageConfigurations"`

	CiContext json.RawMessage `json:"ciContext"`
}

func (v *PreviewEnvironmentInput) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *PreviewEnvironmentInput) __premarshalJSON() (*__premarshalPreviewEnvironmentInput, error) {
	var retval __premarshalPreviewEnvironmentInput

	retval.Credentials = v.Credentials
	{

		dst := &retval.PackageConfigurations
		src := v.PackageConfigurations
		var err error
		*dst, err = scalars.MarshalJSON(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal PreviewEnvironmentInput.PackageConfigurations: %w", err)
		}
	}
	{

		dst := &retval.CiContext
		src := v.CiContext
		var err error
		*dst, err = scalars.MarshalJSON(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal PreviewEnvironmentInput.CiContext: %w", err)
		}
	}
	return &retval, nil
}

// __configurePackageInput is used internally by genqlient
type __configurePackageInput struct {
	OrganizationId string                 `json:"organizationId"`
	TargetId       string                 `json:"targetId"`
	ManifestId     string                 `json:"manifestId"`
	Params         map[string]interface{} `json:"-"`
}

// GetOrganizationId returns __configurePackageInput.OrganizationId, and is useful for accessing the field via an interface.
func (v *__configurePackageInput) GetOrganizationId() string { return v.OrganizationId }

// GetTargetId returns __configurePackageInput.TargetId, and is useful for accessing the field via an interface.
func (v *__configurePackageInput) GetTargetId() string { return v.TargetId }

// GetManifestId returns __configurePackageInput.ManifestId, and is useful for accessing the field via an interface.
func (v *__configurePackageInput) GetManifestId() string { return v.ManifestId }

// GetParams returns __configurePackageInput.Params, and is useful for accessing the field via an interface.
func (v *__configurePackageInput) GetParams() map[string]interface{} { return v.Params }

func (v *__configurePackageInput) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*__configurePackageInput
		Params json.RawMessage `json:"params"`
		graphql.NoUnmarshalJSON
	}
	firstPass.__configurePackageInput = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.Params
		src := firstPass.Params
		if len(src) != 0 && string(src) != "null" {
			err = scalars.UnmarshalJSON(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal __configurePackageInput.Params: %w", err)
			}
		}
	}
	return nil
}

type __premarshal__configurePackageInput struct {
	OrganizationId string `json:"organizationId"`

	TargetId string `json:"targetId"`

	ManifestId string `json:"manifestId"`

	Params json.RawMessage `json:"params"`
}

func (v *__configurePackageInput) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *__configurePackageInput) __premarshalJSON() (*__premarshal__configurePackageInput, error) {
	var retval __premarshal__configurePackageInput

	retval.OrganizationId = v.OrganizationId
	retval.TargetId = v.TargetId
	retval.ManifestId = v.ManifestId
	{

		dst := &retval.Params
		src := v.Params
		var err error
		*dst, err = scalars.MarshalJSON(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal __configurePackageInput.Params: %w", err)
		}
	}
	return &retval, nil
}

// __containerRepositoryInput is used internally by genqlient
type __containerRepositoryInput struct {
	OrgId      string                   `json:"orgId"`
	ArtifactId string                   `json:"artifactId"`
	Input      ContainerRepositoryInput `json:"input"`
}

// GetOrgId returns __containerRepositoryInput.OrgId, and is useful for accessing the field via an interface.
func (v *__containerRepositoryInput) GetOrgId() string { return v.OrgId }

// GetArtifactId returns __containerRepositoryInput.ArtifactId, and is useful for accessing the field via an interface.
func (v *__containerRepositoryInput) GetArtifactId() string { return v.ArtifactId }

// GetInput returns __containerRepositoryInput.Input, and is useful for accessing the field via an interface.
func (v *__containerRepositoryInput) GetInput() ContainerRepositoryInput { return v.Input }

// __createArtifactInput is used internally by genqlient
type __createArtifactInput struct {
	OrganizationId string                 `json:"organizationId"`
	ArtifactName   string                 `json:"artifactName"`
	ArtifactSpecs  map[string]interface{} `json:"-"`
	ArtifactType   string                 `json:"artifactType"`
	ArtifactData   map[string]interface{} `json:"-"`
}

// GetOrganizationId returns __createArtifactInput.OrganizationId, and is useful for accessing the field via an interface.
func (v *__createArtifactInput) GetOrganizationId() string { return v.OrganizationId }

// GetArtifactName returns __createArtifactInput.ArtifactName, and is useful for accessing the field via an interface.
func (v *__createArtifactInput) GetArtifactName() string { return v.ArtifactName }

// GetArtifactSpecs returns __createArtifactInput.ArtifactSpecs, and is useful for accessing the field via an interface.
func (v *__createArtifactInput) GetArtifactSpecs() map[string]interface{} { return v.ArtifactSpecs }

// GetArtifactType returns __createArtifactInput.ArtifactType, and is useful for accessing the field via an interface.
func (v *__createArtifactInput) GetArtifactType() string { return v.ArtifactType }

// GetArtifactData returns __createArtifactInput.ArtifactData, and is useful for accessing the field via an interface.
func (v *__createArtifactInput) GetArtifactData() map[string]interface{} { return v.ArtifactData }

func (v *__createArtifactInput) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*__createArtifactInput
		ArtifactSpecs json.RawMessage `json:"artifactSpecs"`
		ArtifactData  json.RawMessage `json:"artifactData"`
		graphql.NoUnmarshalJSON
	}
	firstPass.__createArtifactInput = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.ArtifactSpecs
		src := firstPass.ArtifactSpecs
		if len(src) != 0 && string(src) != "null" {
			err = scalars.UnmarshalJSON(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal __createArtifactInput.ArtifactSpecs: %w", err)
			}
		}
	}

	{
		dst := &v.ArtifactData
		src := firstPass.ArtifactData
		if len(src) != 0 && string(src) != "null" {
			err = scalars.UnmarshalJSON(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal __createArtifactInput.ArtifactData: %w", err)
			}
		}
	}
	return nil
}

type __premarshal__createArtifactInput struct {
	OrganizationId string `json:"organizationId"`

	ArtifactName string `json:"artifactName"`

	ArtifactSpecs json.RawMessage `json:"artifactSpecs"`

	ArtifactType string `json:"artifactType"`

	ArtifactData json.RawMessage `json:"artifactData"`
}

func (v *__createArtifactInput) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *__createArtifactInput) __premarshalJSON() (*__premarshal__createArtifactInput, error) {
	var retval __premarshal__createArtifactInput

	retval.OrganizationId = v.OrganizationId
	retval.ArtifactName = v.ArtifactName
	{

		dst := &retval.ArtifactSpecs
		src := v.ArtifactSpecs
		var err error
		*dst, err = scalars.MarshalJSON(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal __createArtifactInput.ArtifactSpecs: %w", err)
		}
	}
	retval.ArtifactType = v.ArtifactType
	{

		dst := &retval.ArtifactData
		src := v.ArtifactData
		var err error
		*dst, err = scalars.MarshalJSON(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal __createArtifactInput.ArtifactData: %w", err)
		}
	}
	return &retval, nil
}

// __decommissionPreviewEnvironmentInput is used internally by genqlient
type __decommissionPreviewEnvironmentInput struct {
	OrgId    string `json:"orgId"`
	TargetId string `json:"targetId"`
}

// GetOrgId returns __decommissionPreviewEnvironmentInput.OrgId, and is useful for accessing the field via an interface.
func (v *__decommissionPreviewEnvironmentInput) GetOrgId() string { return v.OrgId }

// GetTargetId returns __decommissionPreviewEnvironmentInput.TargetId, and is useful for accessing the field via an interface.
func (v *__decommissionPreviewEnvironmentInput) GetTargetId() string { return v.TargetId }

// __deployPackageInput is used internally by genqlient
type __deployPackageInput struct {
	OrganizationId string `json:"organizationId"`
	TargetId       string `json:"targetId"`
	ManifestId     string `json:"manifestId"`
	Message        string `json:"message"`
}

// GetOrganizationId returns __deployPackageInput.OrganizationId, and is useful for accessing the field via an interface.
func (v *__deployPackageInput) GetOrganizationId() string { return v.OrganizationId }

// GetTargetId returns __deployPackageInput.TargetId, and is useful for accessing the field via an interface.
func (v *__deployPackageInput) GetTargetId() string { return v.TargetId }

// GetManifestId returns __deployPackageInput.ManifestId, and is useful for accessing the field via an interface.
func (v *__deployPackageInput) GetManifestId() string { return v.ManifestId }

// GetMessage returns __deployPackageInput.Message, and is useful for accessing the field via an interface.
func (v *__deployPackageInput) GetMessage() string { return v.Message }

// __deployPreviewEnvironmentInput is used internally by genqlient
type __deployPreviewEnvironmentInput struct {
	OrganizationId string                  `json:"organizationId"`
	ProjectId      string                  `json:"projectId"`
	Input          PreviewEnvironmentInput `json:"input"`
}

// GetOrganizationId returns __deployPreviewEnvironmentInput.OrganizationId, and is useful for accessing the field via an interface.
func (v *__deployPreviewEnvironmentInput) GetOrganizationId() string { return v.OrganizationId }

// GetProjectId returns __deployPreviewEnvironmentInput.ProjectId, and is useful for accessing the field via an interface.
func (v *__deployPreviewEnvironmentInput) GetProjectId() string { return v.ProjectId }

// GetInput returns __deployPreviewEnvironmentInput.Input, and is useful for accessing the field via an interface.
func (v *__deployPreviewEnvironmentInput) GetInput() PreviewEnvironmentInput { return v.Input }

// __getArtifactDefinitionsInput is used internally by genqlient
type __getArtifactDefinitionsInput struct {
	OrganizationId string `json:"organizationId"`
}

// GetOrganizationId returns __getArtifactDefinitionsInput.OrganizationId, and is useful for accessing the field via an interface.
func (v *__getArtifactDefinitionsInput) GetOrganizationId() string { return v.OrganizationId }

// __getArtifactsByTypeInput is used internally by genqlient
type __getArtifactsByTypeInput struct {
	OrganizationId string `json:"organizationId"`
	ArtifactType   string `json:"artifactType"`
}

// GetOrganizationId returns __getArtifactsByTypeInput.OrganizationId, and is useful for accessing the field via an interface.
func (v *__getArtifactsByTypeInput) GetOrganizationId() string { return v.OrganizationId }

// GetArtifactType returns __getArtifactsByTypeInput.ArtifactType, and is useful for accessing the field via an interface.
func (v *__getArtifactsByTypeInput) GetArtifactType() string { return v.ArtifactType }

// __getDeploymentByIdInput is used internally by genqlient
type __getDeploymentByIdInput struct {
	OrganizationId string `json:"organizationId"`
	Id             string `json:"id"`
}

// GetOrganizationId returns __getDeploymentByIdInput.OrganizationId, and is useful for accessing the field via an interface.
func (v *__getDeploymentByIdInput) GetOrganizationId() string { return v.OrganizationId }

// GetId returns __getDeploymentByIdInput.Id, and is useful for accessing the field via an interface.
func (v *__getDeploymentByIdInput) GetId() string { return v.Id }

// __getPackageByNamingConventionInput is used internally by genqlient
type __getPackageByNamingConventionInput struct {
	OrganizationId string `json:"organizationId"`
	Name           string `json:"name"`
}

// GetOrganizationId returns __getPackageByNamingConventionInput.OrganizationId, and is useful for accessing the field via an interface.
func (v *__getPackageByNamingConventionInput) GetOrganizationId() string { return v.OrganizationId }

// GetName returns __getPackageByNamingConventionInput.Name, and is useful for accessing the field via an interface.
func (v *__getPackageByNamingConventionInput) GetName() string { return v.Name }

// __getProjectByIdInput is used internally by genqlient
type __getProjectByIdInput struct {
	OrganizationId string `json:"organizationId"`
	Id             string `json:"id"`
}

// GetOrganizationId returns __getProjectByIdInput.OrganizationId, and is useful for accessing the field via an interface.
func (v *__getProjectByIdInput) GetOrganizationId() string { return v.OrganizationId }

// GetId returns __getProjectByIdInput.Id, and is useful for accessing the field via an interface.
func (v *__getProjectByIdInput) GetId() string { return v.Id }

// __projectsInput is used internally by genqlient
type __projectsInput struct {
	OrganizationId string `json:"organizationId"`
}

// GetOrganizationId returns __projectsInput.OrganizationId, and is useful for accessing the field via an interface.
func (v *__projectsInput) GetOrganizationId() string { return v.OrganizationId }

// configurePackageConfigurePackagePackagePayload includes the requested fields of the GraphQL type PackagePayload.
type configurePackageConfigurePackagePackagePayload struct {
	// The object created/updated/deleted by the mutation. May be null if mutation failed.
	Result configurePackageConfigurePackagePackagePayloadResultPackage `json:"result"`
	// Indicates if the mutation completed successfully or not.
	Successful bool `json:"successful"`
	// A list of failed validations. May be blank or null if mutation succeeded.
	Messages []MutationValidationError `json:"messages"`
}

// GetResult returns configurePackageConfigurePackagePackagePayload.Result, and is useful for accessing the field via an interface.
func (v *configurePackageConfigurePackagePackagePayload) GetResult() configurePackageConfigurePackagePackagePayloadResultPackage {
	return v.Result
}

// GetSuccessful returns configurePackageConfigurePackagePackagePayload.Successful, and is useful for accessing the field via an interface.
func (v *configurePackageConfigurePackagePackagePayload) GetSuccessful() bool { return v.Successful }

// GetMessages returns configurePackageConfigurePackagePackagePayload.Messages, and is useful for accessing the field via an interface.
func (v *configurePackageConfigurePackagePackagePayload) GetMessages() []MutationValidationError {
	return v.Messages
}

// configurePackageConfigurePackagePackagePayloadResultPackage includes the requested fields of the GraphQL type Package.
type configurePackageConfigurePackagePackagePayloadResultPackage struct {
	Id string `json:"id"`
	// Package configuration parameters
	Params     map[string]interface{} `json:"-"`
	NamePrefix string                 `json:"namePrefix"`
}

// GetId returns configurePackageConfigurePackagePackagePayloadResultPackage.Id, and is useful for accessing the field via an interface.
func (v *configurePackageConfigurePackagePackagePayloadResultPackage) GetId() string { return v.Id }

// GetParams returns configurePackageConfigurePackagePackagePayloadResultPackage.Params, and is useful for accessing the field via an interface.
func (v *configurePackageConfigurePackagePackagePayloadResultPackage) GetParams() map[string]interface{} {
	return v.Params
}

// GetNamePrefix returns configurePackageConfigurePackagePackagePayloadResultPackage.NamePrefix, and is useful for accessing the field via an interface.
func (v *configurePackageConfigurePackagePackagePayloadResultPackage) GetNamePrefix() string {
	return v.NamePrefix
}

func (v *configurePackageConfigurePackagePackagePayloadResultPackage) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*configurePackageConfigurePackagePackagePayloadResultPackage
		Params json.RawMessage `json:"params"`
		graphql.NoUnmarshalJSON
	}
	firstPass.configurePackageConfigurePackagePackagePayloadResultPackage = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.Params
		src := firstPass.Params
		if len(src) != 0 && string(src) != "null" {
			err = scalars.UnmarshalJSON(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal configurePackageConfigurePackagePackagePayloadResultPackage.Params: %w", err)
			}
		}
	}
	return nil
}

type __premarshalconfigurePackageConfigurePackagePackagePayloadResultPackage struct {
	Id string `json:"id"`

	Params json.RawMessage `json:"params"`

	NamePrefix string `json:"namePrefix"`
}

func (v *configurePackageConfigurePackagePackagePayloadResultPackage) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *configurePackageConfigurePackagePackagePayloadResultPackage) __premarshalJSON() (*__premarshalconfigurePackageConfigurePackagePackagePayloadResultPackage, error) {
	var retval __premarshalconfigurePackageConfigurePackagePackagePayloadResultPackage

	retval.Id = v.Id
	{

		dst := &retval.Params
		src := v.Params
		var err error
		*dst, err = scalars.MarshalJSON(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal configurePackageConfigurePackagePackagePayloadResultPackage.Params: %w", err)
		}
	}
	retval.NamePrefix = v.NamePrefix
	return &retval, nil
}

// configurePackageResponse is returned by configurePackage on success.
type configurePackageResponse struct {
	// Update a Package's parameters
	ConfigurePackage configurePackageConfigurePackagePackagePayload `json:"configurePackage"`
}

// GetConfigurePackage returns configurePackageResponse.ConfigurePackage, and is useful for accessing the field via an interface.
func (v *configurePackageResponse) GetConfigurePackage() configurePackageConfigurePackagePackagePayload {
	return v.ConfigurePackage
}

// containerRepositoryContainerRepositoryContainerRepositoryAuth includes the requested fields of the GraphQL type ContainerRepositoryAuth.
type containerRepositoryContainerRepositoryContainerRepositoryAuth struct {
	Token   string `json:"token"`
	RepoUri string `json:"repoUri"`
}

// GetToken returns containerRepositoryContainerRepositoryContainerRepositoryAuth.Token, and is useful for accessing the field via an interface.
func (v *containerRepositoryContainerRepositoryContainerRepositoryAuth) GetToken() string {
	return v.Token
}

// GetRepoUri returns containerRepositoryContainerRepositoryContainerRepositoryAuth.RepoUri, and is useful for accessing the field via an interface.
func (v *containerRepositoryContainerRepositoryContainerRepositoryAuth) GetRepoUri() string {
	return v.RepoUri
}

// containerRepositoryResponse is returned by containerRepository on success.
type containerRepositoryResponse struct {
	ContainerRepository containerRepositoryContainerRepositoryContainerRepositoryAuth `json:"containerRepository"`
}

// GetContainerRepository returns containerRepositoryResponse.ContainerRepository, and is useful for accessing the field via an interface.
func (v *containerRepositoryResponse) GetContainerRepository() containerRepositoryContainerRepositoryContainerRepositoryAuth {
	return v.ContainerRepository
}

// createArtifactCreateArtifactArtifactPayload includes the requested fields of the GraphQL type ArtifactPayload.
type createArtifactCreateArtifactArtifactPayload struct {
	// The object created/updated/deleted by the mutation. May be null if mutation failed.
	Result createArtifactCreateArtifactArtifactPayloadResultArtifact `json:"result"`
	// Indicates if the mutation completed successfully or not.
	Successful bool `json:"successful"`
	// A list of failed validations. May be blank or null if mutation succeeded.
	Messages []MutationValidationError `json:"messages"`
}

// GetResult returns createArtifactCreateArtifactArtifactPayload.Result, and is useful for accessing the field via an interface.
func (v *createArtifactCreateArtifactArtifactPayload) GetResult() createArtifactCreateArtifactArtifactPayloadResultArtifact {
	return v.Result
}

// GetSuccessful returns createArtifactCreateArtifactArtifactPayload.Successful, and is useful for accessing the field via an interface.
func (v *createArtifactCreateArtifactArtifactPayload) GetSuccessful() bool { return v.Successful }

// GetMessages returns createArtifactCreateArtifactArtifactPayload.Messages, and is useful for accessing the field via an interface.
func (v *createArtifactCreateArtifactArtifactPayload) GetMessages() []MutationValidationError {
	return v.Messages
}

// createArtifactCreateArtifactArtifactPayloadResultArtifact includes the requested fields of the GraphQL type Artifact.
type createArtifactCreateArtifactArtifactPayloadResultArtifact struct {
	Name string `json:"name"`
	Id   string `json:"id"`
}

// GetName returns createArtifactCreateArtifactArtifactPayloadResultArtifact.Name, and is useful for accessing the field via an interface.
func (v *createArtifactCreateArtifactArtifactPayloadResultArtifact) GetName() string { return v.Name }

// GetId returns createArtifactCreateArtifactArtifactPayloadResultArtifact.Id, and is useful for accessing the field via an interface.
func (v *createArtifactCreateArtifactArtifactPayloadResultArtifact) GetId() string { return v.Id }

// createArtifactResponse is returned by createArtifact on success.
type createArtifactResponse struct {
	// Create an artifact
	CreateArtifact createArtifactCreateArtifactArtifactPayload `json:"createArtifact"`
}

// GetCreateArtifact returns createArtifactResponse.CreateArtifact, and is useful for accessing the field via an interface.
func (v *createArtifactResponse) GetCreateArtifact() createArtifactCreateArtifactArtifactPayload {
	return v.CreateArtifact
}

// decommissionPreviewEnvironmentDecommissionPreviewEnvironmentEnvironmentPayload includes the requested fields of the GraphQL type EnvironmentPayload.
type decommissionPreviewEnvironmentDecommissionPreviewEnvironmentEnvironmentPayload struct {
	// The object created/updated/deleted by the mutation. May be null if mutation failed.
	Result decommissionPreviewEnvironmentDecommissionPreviewEnvironmentEnvironmentPayloadResultEnvironment `json:"result"`
	// Indicates if the mutation completed successfully or not.
	Successful bool `json:"successful"`
	// A list of failed validations. May be blank or null if mutation succeeded.
	Messages []MutationValidationError `json:"messages"`
}

// GetResult returns decommissionPreviewEnvironmentDecommissionPreviewEnvironmentEnvironmentPayload.Result, and is useful for accessing the field via an interface.
func (v *decommissionPreviewEnvironmentDecommissionPreviewEnvironmentEnvironmentPayload) GetResult() decommissionPreviewEnvironmentDecommissionPreviewEnvironmentEnvironmentPayloadResultEnvironment {
	return v.Result
}

// GetSuccessful returns decommissionPreviewEnvironmentDecommissionPreviewEnvironmentEnvironmentPayload.Successful, and is useful for accessing the field via an interface.
func (v *decommissionPreviewEnvironmentDecommissionPreviewEnvironmentEnvironmentPayload) GetSuccessful() bool {
	return v.Successful
}

// GetMessages returns decommissionPreviewEnvironmentDecommissionPreviewEnvironmentEnvironmentPayload.Messages, and is useful for accessing the field via an interface.
func (v *decommissionPreviewEnvironmentDecommissionPreviewEnvironmentEnvironmentPayload) GetMessages() []MutationValidationError {
	return v.Messages
}

// decommissionPreviewEnvironmentDecommissionPreviewEnvironmentEnvironmentPayloadResultEnvironment includes the requested fields of the GraphQL type Environment.
type decommissionPreviewEnvironmentDecommissionPreviewEnvironmentEnvironmentPayloadResultEnvironment struct {
	Id      string                                                                                                 `json:"id"`
	Slug    string                                                                                                 `json:"slug"`
	Project decommissionPreviewEnvironmentDecommissionPreviewEnvironmentEnvironmentPayloadResultEnvironmentProject `json:"project"`
}

// GetId returns decommissionPreviewEnvironmentDecommissionPreviewEnvironmentEnvironmentPayloadResultEnvironment.Id, and is useful for accessing the field via an interface.
func (v *decommissionPreviewEnvironmentDecommissionPreviewEnvironmentEnvironmentPayloadResultEnvironment) GetId() string {
	return v.Id
}

// GetSlug returns decommissionPreviewEnvironmentDecommissionPreviewEnvironmentEnvironmentPayloadResultEnvironment.Slug, and is useful for accessing the field via an interface.
func (v *decommissionPreviewEnvironmentDecommissionPreviewEnvironmentEnvironmentPayloadResultEnvironment) GetSlug() string {
	return v.Slug
}

// GetProject returns decommissionPreviewEnvironmentDecommissionPreviewEnvironmentEnvironmentPayloadResultEnvironment.Project, and is useful for accessing the field via an interface.
func (v *decommissionPreviewEnvironmentDecommissionPreviewEnvironmentEnvironmentPayloadResultEnvironment) GetProject() decommissionPreviewEnvironmentDecommissionPreviewEnvironmentEnvironmentPayloadResultEnvironmentProject {
	return v.Project
}

// decommissionPreviewEnvironmentDecommissionPreviewEnvironmentEnvironmentPayloadResultEnvironmentProject includes the requested fields of the GraphQL type Project.
type decommissionPreviewEnvironmentDecommissionPreviewEnvironmentEnvironmentPayloadResultEnvironmentProject struct {
	Id   string `json:"id"`
	Slug string `json:"slug"`
}

// GetId returns decommissionPreviewEnvironmentDecommissionPreviewEnvironmentEnvironmentPayloadResultEnvironmentProject.Id, and is useful for accessing the field via an interface.
func (v *decommissionPreviewEnvironmentDecommissionPreviewEnvironmentEnvironmentPayloadResultEnvironmentProject) GetId() string {
	return v.Id
}

// GetSlug returns decommissionPreviewEnvironmentDecommissionPreviewEnvironmentEnvironmentPayloadResultEnvironmentProject.Slug, and is useful for accessing the field via an interface.
func (v *decommissionPreviewEnvironmentDecommissionPreviewEnvironmentEnvironmentPayloadResultEnvironmentProject) GetSlug() string {
	return v.Slug
}

// decommissionPreviewEnvironmentResponse is returned by decommissionPreviewEnvironment on success.
type decommissionPreviewEnvironmentResponse struct {
	DecommissionPreviewEnvironment decommissionPreviewEnvironmentDecommissionPreviewEnvironmentEnvironmentPayload `json:"decommissionPreviewEnvironment"`
}

// GetDecommissionPreviewEnvironment returns decommissionPreviewEnvironmentResponse.DecommissionPreviewEnvironment, and is useful for accessing the field via an interface.
func (v *decommissionPreviewEnvironmentResponse) GetDecommissionPreviewEnvironment() decommissionPreviewEnvironmentDecommissionPreviewEnvironmentEnvironmentPayload {
	return v.DecommissionPreviewEnvironment
}

// deployPackageDeployPackageDeploymentPayload includes the requested fields of the GraphQL type DeploymentPayload.
type deployPackageDeployPackageDeploymentPayload struct {
	// Indicates if the mutation completed successfully or not.
	Successful bool `json:"successful"`
	// The object created/updated/deleted by the mutation. May be null if mutation failed.
	Result deployPackageDeployPackageDeploymentPayloadResultDeployment `json:"result"`
	// A list of failed validations. May be blank or null if mutation succeeded.
	Messages []MutationValidationError `json:"messages"`
}

// GetSuccessful returns deployPackageDeployPackageDeploymentPayload.Successful, and is useful for accessing the field via an interface.
func (v *deployPackageDeployPackageDeploymentPayload) GetSuccessful() bool { return v.Successful }

// GetResult returns deployPackageDeployPackageDeploymentPayload.Result, and is useful for accessing the field via an interface.
func (v *deployPackageDeployPackageDeploymentPayload) GetResult() deployPackageDeployPackageDeploymentPayloadResultDeployment {
	return v.Result
}

// GetMessages returns deployPackageDeployPackageDeploymentPayload.Messages, and is useful for accessing the field via an interface.
func (v *deployPackageDeployPackageDeploymentPayload) GetMessages() []MutationValidationError {
	return v.Messages
}

// deployPackageDeployPackageDeploymentPayloadResultDeployment includes the requested fields of the GraphQL type Deployment.
type deployPackageDeployPackageDeploymentPayloadResultDeployment struct {
	Id string `json:"id"`
}

// GetId returns deployPackageDeployPackageDeploymentPayloadResultDeployment.Id, and is useful for accessing the field via an interface.
func (v *deployPackageDeployPackageDeploymentPayloadResultDeployment) GetId() string { return v.Id }

// deployPackageResponse is returned by deployPackage on success.
type deployPackageResponse struct {
	// Enqueues a package for deployment
	DeployPackage deployPackageDeployPackageDeploymentPayload `json:"deployPackage"`
}

// GetDeployPackage returns deployPackageResponse.DeployPackage, and is useful for accessing the field via an interface.
func (v *deployPackageResponse) GetDeployPackage() deployPackageDeployPackageDeploymentPayload {
	return v.DeployPackage
}

// deployPreviewEnvironmentDeployPreviewEnvironmentEnvironmentPayload includes the requested fields of the GraphQL type EnvironmentPayload.
type deployPreviewEnvironmentDeployPreviewEnvironmentEnvironmentPayload struct {
	// Indicates if the mutation completed successfully or not.
	Successful bool `json:"successful"`
	// The object created/updated/deleted by the mutation. May be null if mutation failed.
	Result deployPreviewEnvironmentDeployPreviewEnvironmentEnvironmentPayloadResultEnvironment `json:"result"`
	// A list of failed validations. May be blank or null if mutation succeeded.
	Messages []MutationValidationError `json:"messages"`
}

// GetSuccessful returns deployPreviewEnvironmentDeployPreviewEnvironmentEnvironmentPayload.Successful, and is useful for accessing the field via an interface.
func (v *deployPreviewEnvironmentDeployPreviewEnvironmentEnvironmentPayload) GetSuccessful() bool {
	return v.Successful
}

// GetResult returns deployPreviewEnvironmentDeployPreviewEnvironmentEnvironmentPayload.Result, and is useful for accessing the field via an interface.
func (v *deployPreviewEnvironmentDeployPreviewEnvironmentEnvironmentPayload) GetResult() deployPreviewEnvironmentDeployPreviewEnvironmentEnvironmentPayloadResultEnvironment {
	return v.Result
}

// GetMessages returns deployPreviewEnvironmentDeployPreviewEnvironmentEnvironmentPayload.Messages, and is useful for accessing the field via an interface.
func (v *deployPreviewEnvironmentDeployPreviewEnvironmentEnvironmentPayload) GetMessages() []MutationValidationError {
	return v.Messages
}

// deployPreviewEnvironmentDeployPreviewEnvironmentEnvironmentPayloadResultEnvironment includes the requested fields of the GraphQL type Environment.
type deployPreviewEnvironmentDeployPreviewEnvironmentEnvironmentPayloadResultEnvironment struct {
	Id      string                                                                                     `json:"id"`
	Slug    string                                                                                     `json:"slug"`
	Project deployPreviewEnvironmentDeployPreviewEnvironmentEnvironmentPayloadResultEnvironmentProject `json:"project"`
}

// GetId returns deployPreviewEnvironmentDeployPreviewEnvironmentEnvironmentPayloadResultEnvironment.Id, and is useful for accessing the field via an interface.
func (v *deployPreviewEnvironmentDeployPreviewEnvironmentEnvironmentPayloadResultEnvironment) GetId() string {
	return v.Id
}

// GetSlug returns deployPreviewEnvironmentDeployPreviewEnvironmentEnvironmentPayloadResultEnvironment.Slug, and is useful for accessing the field via an interface.
func (v *deployPreviewEnvironmentDeployPreviewEnvironmentEnvironmentPayloadResultEnvironment) GetSlug() string {
	return v.Slug
}

// GetProject returns deployPreviewEnvironmentDeployPreviewEnvironmentEnvironmentPayloadResultEnvironment.Project, and is useful for accessing the field via an interface.
func (v *deployPreviewEnvironmentDeployPreviewEnvironmentEnvironmentPayloadResultEnvironment) GetProject() deployPreviewEnvironmentDeployPreviewEnvironmentEnvironmentPayloadResultEnvironmentProject {
	return v.Project
}

// deployPreviewEnvironmentDeployPreviewEnvironmentEnvironmentPayloadResultEnvironmentProject includes the requested fields of the GraphQL type Project.
type deployPreviewEnvironmentDeployPreviewEnvironmentEnvironmentPayloadResultEnvironmentProject struct {
	Id   string `json:"id"`
	Slug string `json:"slug"`
}

// GetId returns deployPreviewEnvironmentDeployPreviewEnvironmentEnvironmentPayloadResultEnvironmentProject.Id, and is useful for accessing the field via an interface.
func (v *deployPreviewEnvironmentDeployPreviewEnvironmentEnvironmentPayloadResultEnvironmentProject) GetId() string {
	return v.Id
}

// GetSlug returns deployPreviewEnvironmentDeployPreviewEnvironmentEnvironmentPayloadResultEnvironmentProject.Slug, and is useful for accessing the field via an interface.
func (v *deployPreviewEnvironmentDeployPreviewEnvironmentEnvironmentPayloadResultEnvironmentProject) GetSlug() string {
	return v.Slug
}

// deployPreviewEnvironmentResponse is returned by deployPreviewEnvironment on success.
type deployPreviewEnvironmentResponse struct {
	// Deploy a Preview Environment
	DeployPreviewEnvironment deployPreviewEnvironmentDeployPreviewEnvironmentEnvironmentPayload `json:"deployPreviewEnvironment"`
}

// GetDeployPreviewEnvironment returns deployPreviewEnvironmentResponse.DeployPreviewEnvironment, and is useful for accessing the field via an interface.
func (v *deployPreviewEnvironmentResponse) GetDeployPreviewEnvironment() deployPreviewEnvironmentDeployPreviewEnvironmentEnvironmentPayload {
	return v.DeployPreviewEnvironment
}

// getArtifactDefinitionsArtifactDefinitionsArtifactDefinition includes the requested fields of the GraphQL type ArtifactDefinition.
type getArtifactDefinitionsArtifactDefinitionsArtifactDefinition struct {
	// The name of this type. Organization scoped: my-org/aws-iam-role
	Name   string                 `json:"name"`
	Schema map[string]interface{} `json:"-"`
}

// GetName returns getArtifactDefinitionsArtifactDefinitionsArtifactDefinition.Name, and is useful for accessing the field via an interface.
func (v *getArtifactDefinitionsArtifactDefinitionsArtifactDefinition) GetName() string { return v.Name }

// GetSchema returns getArtifactDefinitionsArtifactDefinitionsArtifactDefinition.Schema, and is useful for accessing the field via an interface.
func (v *getArtifactDefinitionsArtifactDefinitionsArtifactDefinition) GetSchema() map[string]interface{} {
	return v.Schema
}

func (v *getArtifactDefinitionsArtifactDefinitionsArtifactDefinition) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*getArtifactDefinitionsArtifactDefinitionsArtifactDefinition
		Schema json.RawMessage `json:"schema"`
		graphql.NoUnmarshalJSON
	}
	firstPass.getArtifactDefinitionsArtifactDefinitionsArtifactDefinition = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.Schema
		src := firstPass.Schema
		if len(src) != 0 && string(src) != "null" {
			err = scalars.UnmarshalJSON(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal getArtifactDefinitionsArtifactDefinitionsArtifactDefinition.Schema: %w", err)
			}
		}
	}
	return nil
}

type __premarshalgetArtifactDefinitionsArtifactDefinitionsArtifactDefinition struct {
	Name string `json:"name"`

	Schema json.RawMessage `json:"schema"`
}

func (v *getArtifactDefinitionsArtifactDefinitionsArtifactDefinition) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *getArtifactDefinitionsArtifactDefinitionsArtifactDefinition) __premarshalJSON() (*__premarshalgetArtifactDefinitionsArtifactDefinitionsArtifactDefinition, error) {
	var retval __premarshalgetArtifactDefinitionsArtifactDefinitionsArtifactDefinition

	retval.Name = v.Name
	{

		dst := &retval.Schema
		src := v.Schema
		var err error
		*dst, err = scalars.MarshalJSON(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal getArtifactDefinitionsArtifactDefinitionsArtifactDefinition.Schema: %w", err)
		}
	}
	return &retval, nil
}

// getArtifactDefinitionsResponse is returned by getArtifactDefinitions on success.
type getArtifactDefinitionsResponse struct {
	ArtifactDefinitions []getArtifactDefinitionsArtifactDefinitionsArtifactDefinition `json:"artifactDefinitions"`
}

// GetArtifactDefinitions returns getArtifactDefinitionsResponse.ArtifactDefinitions, and is useful for accessing the field via an interface.
func (v *getArtifactDefinitionsResponse) GetArtifactDefinitions() []getArtifactDefinitionsArtifactDefinitionsArtifactDefinition {
	return v.ArtifactDefinitions
}

// getArtifactsByTypeArtifactsPaginatedArtifacts includes the requested fields of the GraphQL type PaginatedArtifacts.
type getArtifactsByTypeArtifactsPaginatedArtifacts struct {
	// A cursor to the next page of items in the list.
	Next string `json:"next"`
	// A list of type artifact.
	Items []getArtifactsByTypeArtifactsPaginatedArtifactsItemsArtifact `json:"items"`
}

// GetNext returns getArtifactsByTypeArtifactsPaginatedArtifacts.Next, and is useful for accessing the field via an interface.
func (v *getArtifactsByTypeArtifactsPaginatedArtifacts) GetNext() string { return v.Next }

// GetItems returns getArtifactsByTypeArtifactsPaginatedArtifacts.Items, and is useful for accessing the field via an interface.
func (v *getArtifactsByTypeArtifactsPaginatedArtifacts) GetItems() []getArtifactsByTypeArtifactsPaginatedArtifactsItemsArtifact {
	return v.Items
}

// getArtifactsByTypeArtifactsPaginatedArtifactsItemsArtifact includes the requested fields of the GraphQL type Artifact.
type getArtifactsByTypeArtifactsPaginatedArtifactsItemsArtifact struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// GetId returns getArtifactsByTypeArtifactsPaginatedArtifactsItemsArtifact.Id, and is useful for accessing the field via an interface.
func (v *getArtifactsByTypeArtifactsPaginatedArtifactsItemsArtifact) GetId() string { return v.Id }

// GetName returns getArtifactsByTypeArtifactsPaginatedArtifactsItemsArtifact.Name, and is useful for accessing the field via an interface.
func (v *getArtifactsByTypeArtifactsPaginatedArtifactsItemsArtifact) GetName() string { return v.Name }

// getArtifactsByTypeResponse is returned by getArtifactsByType on success.
type getArtifactsByTypeResponse struct {
	// List all artifacts
	Artifacts getArtifactsByTypeArtifactsPaginatedArtifacts `json:"artifacts"`
}

// GetArtifacts returns getArtifactsByTypeResponse.Artifacts, and is useful for accessing the field via an interface.
func (v *getArtifactsByTypeResponse) GetArtifacts() getArtifactsByTypeArtifactsPaginatedArtifacts {
	return v.Artifacts
}

// getDeploymentByIdDeployment includes the requested fields of the GraphQL type Deployment.
type getDeploymentByIdDeployment struct {
	Id     string `json:"id"`
	Status string `json:"status"`
}

// GetId returns getDeploymentByIdDeployment.Id, and is useful for accessing the field via an interface.
func (v *getDeploymentByIdDeployment) GetId() string { return v.Id }

// GetStatus returns getDeploymentByIdDeployment.Status, and is useful for accessing the field via an interface.
func (v *getDeploymentByIdDeployment) GetStatus() string { return v.Status }

// getDeploymentByIdResponse is returned by getDeploymentById on success.
type getDeploymentByIdResponse struct {
	Deployment getDeploymentByIdDeployment `json:"deployment"`
}

// GetDeployment returns getDeploymentByIdResponse.Deployment, and is useful for accessing the field via an interface.
func (v *getDeploymentByIdResponse) GetDeployment() getDeploymentByIdDeployment { return v.Deployment }

// getPackageByNamingConventionGetPackageByNamingConventionPackage includes the requested fields of the GraphQL type Package.
type getPackageByNamingConventionGetPackageByNamingConventionPackage struct {
	Id         string `json:"id"`
	NamePrefix string `json:"namePrefix"`
	// Package configuration parameters
	Params           map[string]interface{}                                                          `json:"-"`
	Manifest         getPackageByNamingConventionGetPackageByNamingConventionPackageManifest         `json:"manifest"`
	ActiveDeployment getPackageByNamingConventionGetPackageByNamingConventionPackageActiveDeployment `json:"activeDeployment"`
	// The environment this package will be deployed to
	Environment getPackageByNamingConventionGetPackageByNamingConventionPackageEnvironment `json:"environment"`
}

// GetId returns getPackageByNamingConventionGetPackageByNamingConventionPackage.Id, and is useful for accessing the field via an interface.
func (v *getPackageByNamingConventionGetPackageByNamingConventionPackage) GetId() string { return v.Id }

// GetNamePrefix returns getPackageByNamingConventionGetPackageByNamingConventionPackage.NamePrefix, and is useful for accessing the field via an interface.
func (v *getPackageByNamingConventionGetPackageByNamingConventionPackage) GetNamePrefix() string {
	return v.NamePrefix
}

// GetParams returns getPackageByNamingConventionGetPackageByNamingConventionPackage.Params, and is useful for accessing the field via an interface.
func (v *getPackageByNamingConventionGetPackageByNamingConventionPackage) GetParams() map[string]interface{} {
	return v.Params
}

// GetManifest returns getPackageByNamingConventionGetPackageByNamingConventionPackage.Manifest, and is useful for accessing the field via an interface.
func (v *getPackageByNamingConventionGetPackageByNamingConventionPackage) GetManifest() getPackageByNamingConventionGetPackageByNamingConventionPackageManifest {
	return v.Manifest
}

// GetActiveDeployment returns getPackageByNamingConventionGetPackageByNamingConventionPackage.ActiveDeployment, and is useful for accessing the field via an interface.
func (v *getPackageByNamingConventionGetPackageByNamingConventionPackage) GetActiveDeployment() getPackageByNamingConventionGetPackageByNamingConventionPackageActiveDeployment {
	return v.ActiveDeployment
}

// GetEnvironment returns getPackageByNamingConventionGetPackageByNamingConventionPackage.Environment, and is useful for accessing the field via an interface.
func (v *getPackageByNamingConventionGetPackageByNamingConventionPackage) GetEnvironment() getPackageByNamingConventionGetPackageByNamingConventionPackageEnvironment {
	return v.Environment
}

func (v *getPackageByNamingConventionGetPackageByNamingConventionPackage) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*getPackageByNamingConventionGetPackageByNamingConventionPackage
		Params json.RawMessage `json:"params"`
		graphql.NoUnmarshalJSON
	}
	firstPass.getPackageByNamingConventionGetPackageByNamingConventionPackage = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.Params
		src := firstPass.Params
		if len(src) != 0 && string(src) != "null" {
			err = scalars.UnmarshalJSON(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal getPackageByNamingConventionGetPackageByNamingConventionPackage.Params: %w", err)
			}
		}
	}
	return nil
}

type __premarshalgetPackageByNamingConventionGetPackageByNamingConventionPackage struct {
	Id string `json:"id"`

	NamePrefix string `json:"namePrefix"`

	Params json.RawMessage `json:"params"`

	Manifest getPackageByNamingConventionGetPackageByNamingConventionPackageManifest `json:"manifest"`

	ActiveDeployment getPackageByNamingConventionGetPackageByNamingConventionPackageActiveDeployment `json:"activeDeployment"`

	Environment getPackageByNamingConventionGetPackageByNamingConventionPackageEnvironment `json:"environment"`
}

func (v *getPackageByNamingConventionGetPackageByNamingConventionPackage) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *getPackageByNamingConventionGetPackageByNamingConventionPackage) __premarshalJSON() (*__premarshalgetPackageByNamingConventionGetPackageByNamingConventionPackage, error) {
	var retval __premarshalgetPackageByNamingConventionGetPackageByNamingConventionPackage

	retval.Id = v.Id
	retval.NamePrefix = v.NamePrefix
	{

		dst := &retval.Params
		src := v.Params
		var err error
		*dst, err = scalars.MarshalJSON(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal getPackageByNamingConventionGetPackageByNamingConventionPackage.Params: %w", err)
		}
	}
	retval.Manifest = v.Manifest
	retval.ActiveDeployment = v.ActiveDeployment
	retval.Environment = v.Environment
	return &retval, nil
}

// getPackageByNamingConventionGetPackageByNamingConventionPackageActiveDeployment includes the requested fields of the GraphQL type Deployment.
type getPackageByNamingConventionGetPackageByNamingConventionPackageActiveDeployment struct {
	Id     string `json:"id"`
	Status string `json:"status"`
}

// GetId returns getPackageByNamingConventionGetPackageByNamingConventionPackageActiveDeployment.Id, and is useful for accessing the field via an interface.
func (v *getPackageByNamingConventionGetPackageByNamingConventionPackageActiveDeployment) GetId() string {
	return v.Id
}

// GetStatus returns getPackageByNamingConventionGetPackageByNamingConventionPackageActiveDeployment.Status, and is useful for accessing the field via an interface.
func (v *getPackageByNamingConventionGetPackageByNamingConventionPackageActiveDeployment) GetStatus() string {
	return v.Status
}

// getPackageByNamingConventionGetPackageByNamingConventionPackageEnvironment includes the requested fields of the GraphQL type Environment.
type getPackageByNamingConventionGetPackageByNamingConventionPackageEnvironment struct {
	Id      string                                                                            `json:"id"`
	Slug    string                                                                            `json:"slug"`
	Project getPackageByNamingConventionGetPackageByNamingConventionPackageEnvironmentProject `json:"project"`
}

// GetId returns getPackageByNamingConventionGetPackageByNamingConventionPackageEnvironment.Id, and is useful for accessing the field via an interface.
func (v *getPackageByNamingConventionGetPackageByNamingConventionPackageEnvironment) GetId() string {
	return v.Id
}

// GetSlug returns getPackageByNamingConventionGetPackageByNamingConventionPackageEnvironment.Slug, and is useful for accessing the field via an interface.
func (v *getPackageByNamingConventionGetPackageByNamingConventionPackageEnvironment) GetSlug() string {
	return v.Slug
}

// GetProject returns getPackageByNamingConventionGetPackageByNamingConventionPackageEnvironment.Project, and is useful for accessing the field via an interface.
func (v *getPackageByNamingConventionGetPackageByNamingConventionPackageEnvironment) GetProject() getPackageByNamingConventionGetPackageByNamingConventionPackageEnvironmentProject {
	return v.Project
}

// getPackageByNamingConventionGetPackageByNamingConventionPackageEnvironmentProject includes the requested fields of the GraphQL type Project.
type getPackageByNamingConventionGetPackageByNamingConventionPackageEnvironmentProject struct {
	Id   string `json:"id"`
	Slug string `json:"slug"`
}

// GetId returns getPackageByNamingConventionGetPackageByNamingConventionPackageEnvironmentProject.Id, and is useful for accessing the field via an interface.
func (v *getPackageByNamingConventionGetPackageByNamingConventionPackageEnvironmentProject) GetId() string {
	return v.Id
}

// GetSlug returns getPackageByNamingConventionGetPackageByNamingConventionPackageEnvironmentProject.Slug, and is useful for accessing the field via an interface.
func (v *getPackageByNamingConventionGetPackageByNamingConventionPackageEnvironmentProject) GetSlug() string {
	return v.Slug
}

// getPackageByNamingConventionGetPackageByNamingConventionPackageManifest includes the requested fields of the GraphQL type Manifest.
type getPackageByNamingConventionGetPackageByNamingConventionPackageManifest struct {
	Id     string                                                                        `json:"id"`
	Bundle getPackageByNamingConventionGetPackageByNamingConventionPackageManifestBundle `json:"bundle"`
}

// GetId returns getPackageByNamingConventionGetPackageByNamingConventionPackageManifest.Id, and is useful for accessing the field via an interface.
func (v *getPackageByNamingConventionGetPackageByNamingConventionPackageManifest) GetId() string {
	return v.Id
}

// GetBundle returns getPackageByNamingConventionGetPackageByNamingConventionPackageManifest.Bundle, and is useful for accessing the field via an interface.
func (v *getPackageByNamingConventionGetPackageByNamingConventionPackageManifest) GetBundle() getPackageByNamingConventionGetPackageByNamingConventionPackageManifestBundle {
	return v.Bundle
}

// getPackageByNamingConventionGetPackageByNamingConventionPackageManifestBundle includes the requested fields of the GraphQL type Bundle.
type getPackageByNamingConventionGetPackageByNamingConventionPackageManifestBundle struct {
	Name string `json:"name"`
}

// GetName returns getPackageByNamingConventionGetPackageByNamingConventionPackageManifestBundle.Name, and is useful for accessing the field via an interface.
func (v *getPackageByNamingConventionGetPackageByNamingConventionPackageManifestBundle) GetName() string {
	return v.Name
}

// getPackageByNamingConventionResponse is returned by getPackageByNamingConvention on success.
type getPackageByNamingConventionResponse struct {
	// Finds a package by its naming convention, the name prefix (project-target-manifest) without the random unique suffix.
	GetPackageByNamingConvention getPackageByNamingConventionGetPackageByNamingConventionPackage `json:"getPackageByNamingConvention"`
}

// GetGetPackageByNamingConvention returns getPackageByNamingConventionResponse.GetPackageByNamingConvention, and is useful for accessing the field via an interface.
func (v *getPackageByNamingConventionResponse) GetGetPackageByNamingConvention() getPackageByNamingConventionGetPackageByNamingConventionPackage {
	return v.GetPackageByNamingConvention
}

// getProjectByIdProject includes the requested fields of the GraphQL type Project.
type getProjectByIdProject struct {
	Id            string                 `json:"id"`
	Name          string                 `json:"name"`
	DefaultParams map[string]interface{} `json:"-"`
	Slug          string                 `json:"slug"`
	Description   string                 `json:"description"`
}

// GetId returns getProjectByIdProject.Id, and is useful for accessing the field via an interface.
func (v *getProjectByIdProject) GetId() string { return v.Id }

// GetName returns getProjectByIdProject.Name, and is useful for accessing the field via an interface.
func (v *getProjectByIdProject) GetName() string { return v.Name }

// GetDefaultParams returns getProjectByIdProject.DefaultParams, and is useful for accessing the field via an interface.
func (v *getProjectByIdProject) GetDefaultParams() map[string]interface{} { return v.DefaultParams }

// GetSlug returns getProjectByIdProject.Slug, and is useful for accessing the field via an interface.
func (v *getProjectByIdProject) GetSlug() string { return v.Slug }

// GetDescription returns getProjectByIdProject.Description, and is useful for accessing the field via an interface.
func (v *getProjectByIdProject) GetDescription() string { return v.Description }

func (v *getProjectByIdProject) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*getProjectByIdProject
		DefaultParams json.RawMessage `json:"defaultParams"`
		graphql.NoUnmarshalJSON
	}
	firstPass.getProjectByIdProject = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.DefaultParams
		src := firstPass.DefaultParams
		if len(src) != 0 && string(src) != "null" {
			err = scalars.UnmarshalJSON(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal getProjectByIdProject.DefaultParams: %w", err)
			}
		}
	}
	return nil
}

type __premarshalgetProjectByIdProject struct {
	Id string `json:"id"`

	Name string `json:"name"`

	DefaultParams json.RawMessage `json:"defaultParams"`

	Slug string `json:"slug"`

	Description string `json:"description"`
}

func (v *getProjectByIdProject) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *getProjectByIdProject) __premarshalJSON() (*__premarshalgetProjectByIdProject, error) {
	var retval __premarshalgetProjectByIdProject

	retval.Id = v.Id
	retval.Name = v.Name
	{

		dst := &retval.DefaultParams
		src := v.DefaultParams
		var err error
		*dst, err = scalars.MarshalJSON(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal getProjectByIdProject.DefaultParams: %w", err)
		}
	}
	retval.Slug = v.Slug
	retval.Description = v.Description
	return &retval, nil
}

// getProjectByIdResponse is returned by getProjectById on success.
type getProjectByIdResponse struct {
	Project getProjectByIdProject `json:"project"`
}

// GetProject returns getProjectByIdResponse.Project, and is useful for accessing the field via an interface.
func (v *getProjectByIdResponse) GetProject() getProjectByIdProject { return v.Project }

// projectsProjectsProject includes the requested fields of the GraphQL type Project.
type projectsProjectsProject struct {
	Name          string                 `json:"name"`
	Id            string                 `json:"id"`
	Slug          string                 `json:"slug"`
	Description   string                 `json:"description"`
	DefaultParams map[string]interface{} `json:"-"`
	// Cloud provider costs for this project
	Cost projectsProjectsProjectCost `json:"cost"`
}

// GetName returns projectsProjectsProject.Name, and is useful for accessing the field via an interface.
func (v *projectsProjectsProject) GetName() string { return v.Name }

// GetId returns projectsProjectsProject.Id, and is useful for accessing the field via an interface.
func (v *projectsProjectsProject) GetId() string { return v.Id }

// GetSlug returns projectsProjectsProject.Slug, and is useful for accessing the field via an interface.
func (v *projectsProjectsProject) GetSlug() string { return v.Slug }

// GetDescription returns projectsProjectsProject.Description, and is useful for accessing the field via an interface.
func (v *projectsProjectsProject) GetDescription() string { return v.Description }

// GetDefaultParams returns projectsProjectsProject.DefaultParams, and is useful for accessing the field via an interface.
func (v *projectsProjectsProject) GetDefaultParams() map[string]interface{} { return v.DefaultParams }

// GetCost returns projectsProjectsProject.Cost, and is useful for accessing the field via an interface.
func (v *projectsProjectsProject) GetCost() projectsProjectsProjectCost { return v.Cost }

func (v *projectsProjectsProject) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*projectsProjectsProject
		DefaultParams json.RawMessage `json:"defaultParams"`
		graphql.NoUnmarshalJSON
	}
	firstPass.projectsProjectsProject = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.DefaultParams
		src := firstPass.DefaultParams
		if len(src) != 0 && string(src) != "null" {
			err = scalars.UnmarshalJSON(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal projectsProjectsProject.DefaultParams: %w", err)
			}
		}
	}
	return nil
}

type __premarshalprojectsProjectsProject struct {
	Name string `json:"name"`

	Id string `json:"id"`

	Slug string `json:"slug"`

	Description string `json:"description"`

	DefaultParams json.RawMessage `json:"defaultParams"`

	Cost projectsProjectsProjectCost `json:"cost"`
}

func (v *projectsProjectsProject) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *projectsProjectsProject) __premarshalJSON() (*__premarshalprojectsProjectsProject, error) {
	var retval __premarshalprojectsProjectsProject

	retval.Name = v.Name
	retval.Id = v.Id
	retval.Slug = v.Slug
	retval.Description = v.Description
	{

		dst := &retval.DefaultParams
		src := v.DefaultParams
		var err error
		*dst, err = scalars.MarshalJSON(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal projectsProjectsProject.DefaultParams: %w", err)
		}
	}
	retval.Cost = v.Cost
	return &retval, nil
}

// projectsProjectsProjectCost includes the requested fields of the GraphQL type Cost.
type projectsProjectsProjectCost struct {
	Monthly projectsProjectsProjectCostMonthlySummary `json:"monthly"`
	Daily   projectsProjectsProjectCostDailySummary   `json:"daily"`
}

// GetMonthly returns projectsProjectsProjectCost.Monthly, and is useful for accessing the field via an interface.
func (v *projectsProjectsProjectCost) GetMonthly() projectsProjectsProjectCostMonthlySummary {
	return v.Monthly
}

// GetDaily returns projectsProjectsProjectCost.Daily, and is useful for accessing the field via an interface.
func (v *projectsProjectsProjectCost) GetDaily() projectsProjectsProjectCostDailySummary {
	return v.Daily
}

// projectsProjectsProjectCostDailySummary includes the requested fields of the GraphQL type Summary.
type projectsProjectsProjectCostDailySummary struct {
	Average projectsProjectsProjectCostDailySummaryAverageCostSample `json:"average"`
}

// GetAverage returns projectsProjectsProjectCostDailySummary.Average, and is useful for accessing the field via an interface.
func (v *projectsProjectsProjectCostDailySummary) GetAverage() projectsProjectsProjectCostDailySummaryAverageCostSample {
	return v.Average
}

// projectsProjectsProjectCostDailySummaryAverageCostSample includes the requested fields of the GraphQL type CostSample.
type projectsProjectsProjectCostDailySummaryAverageCostSample struct {
	Amount float64 `json:"amount"`
}

// GetAmount returns projectsProjectsProjectCostDailySummaryAverageCostSample.Amount, and is useful for accessing the field via an interface.
func (v *projectsProjectsProjectCostDailySummaryAverageCostSample) GetAmount() float64 {
	return v.Amount
}

// projectsProjectsProjectCostMonthlySummary includes the requested fields of the GraphQL type Summary.
type projectsProjectsProjectCostMonthlySummary struct {
	Average projectsProjectsProjectCostMonthlySummaryAverageCostSample `json:"average"`
}

// GetAverage returns projectsProjectsProjectCostMonthlySummary.Average, and is useful for accessing the field via an interface.
func (v *projectsProjectsProjectCostMonthlySummary) GetAverage() projectsProjectsProjectCostMonthlySummaryAverageCostSample {
	return v.Average
}

// projectsProjectsProjectCostMonthlySummaryAverageCostSample includes the requested fields of the GraphQL type CostSample.
type projectsProjectsProjectCostMonthlySummaryAverageCostSample struct {
	Amount float64 `json:"amount"`
}

// GetAmount returns projectsProjectsProjectCostMonthlySummaryAverageCostSample.Amount, and is useful for accessing the field via an interface.
func (v *projectsProjectsProjectCostMonthlySummaryAverageCostSample) GetAmount() float64 {
	return v.Amount
}

// projectsResponse is returned by projects on success.
type projectsResponse struct {
	Projects []projectsProjectsProject `json:"projects"`
}

// GetProjects returns projectsResponse.Projects, and is useful for accessing the field via an interface.
func (v *projectsResponse) GetProjects() []projectsProjectsProject { return v.Projects }

// The query or mutation executed by configurePackage.
const configurePackage_Operation = `
mutation configurePackage ($organizationId: ID!, $targetId: ID!, $manifestId: ID!, $params: JSON!) {
	configurePackage(organizationId: $organizationId, targetId: $targetId, manifestId: $manifestId, params: $params) {
		result {
			id
			params
			namePrefix
		}
		successful
		messages {
			message
		}
	}
}
`

func configurePackage(
	ctx context.Context,
	client graphql.Client,
	organizationId string,
	targetId string,
	manifestId string,
	params map[string]interface{},
) (*configurePackageResponse, error) {
	req := &graphql.Request{
		OpName: "configurePackage",
		Query:  configurePackage_Operation,
		Variables: &__configurePackageInput{
			OrganizationId: organizationId,
			TargetId:       targetId,
			ManifestId:     manifestId,
			Params:         params,
		},
	}
	var err error

	var data configurePackageResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by containerRepository.
const containerRepository_Operation = `
query containerRepository ($orgId: ID!, $artifactId: ID!, $input: ContainerRepositoryInput!) {
	containerRepository(organizationId: $orgId, artifactId: $artifactId, input: $input) {
		token
		repoUri
	}
}
`

func containerRepository(
	ctx context.Context,
	client graphql.Client,
	orgId string,
	artifactId string,
	input ContainerRepositoryInput,
) (*containerRepositoryResponse, error) {
	req := &graphql.Request{
		OpName: "containerRepository",
		Query:  containerRepository_Operation,
		Variables: &__containerRepositoryInput{
			OrgId:      orgId,
			ArtifactId: artifactId,
			Input:      input,
		},
	}
	var err error

	var data containerRepositoryResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by createArtifact.
const createArtifact_Operation = `
mutation createArtifact ($organizationId: ID!, $artifactName: String!, $artifactSpecs: JSON!, $artifactType: String!, $artifactData: JSON!) {
	createArtifact(organizationId: $organizationId, name: $artifactName, specs: $artifactSpecs, type: $artifactType, data: $artifactData) {
		result {
			name
			id
		}
		successful
		messages {
			message
		}
	}
}
`

func createArtifact(
	ctx context.Context,
	client graphql.Client,
	organizationId string,
	artifactName string,
	artifactSpecs map[string]interface{},
	artifactType string,
	artifactData map[string]interface{},
) (*createArtifactResponse, error) {
	req := &graphql.Request{
		OpName: "createArtifact",
		Query:  createArtifact_Operation,
		Variables: &__createArtifactInput{
			OrganizationId: organizationId,
			ArtifactName:   artifactName,
			ArtifactSpecs:  artifactSpecs,
			ArtifactType:   artifactType,
			ArtifactData:   artifactData,
		},
	}
	var err error

	var data createArtifactResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by decommissionPreviewEnvironment.
const decommissionPreviewEnvironment_Operation = `
mutation decommissionPreviewEnvironment ($orgId: ID!, $targetId: ID!) {
	decommissionPreviewEnvironment(organizationId: $orgId, targetId: $targetId) {
		result {
			id
			slug
			project {
				id
				slug
			}
		}
		successful
		messages {
			message
		}
	}
}
`

func decommissionPreviewEnvironment(
	ctx context.Context,
	client graphql.Client,
	orgId string,
	targetId string,
) (*decommissionPreviewEnvironmentResponse, error) {
	req := &graphql.Request{
		OpName: "decommissionPreviewEnvironment",
		Query:  decommissionPreviewEnvironment_Operation,
		Variables: &__decommissionPreviewEnvironmentInput{
			OrgId:    orgId,
			TargetId: targetId,
		},
	}
	var err error

	var data decommissionPreviewEnvironmentResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by deployPackage.
const deployPackage_Operation = `
mutation deployPackage ($organizationId: ID!, $targetId: ID!, $manifestId: ID!, $message: String!) {
	deployPackage(organizationId: $organizationId, manifestId: $manifestId, targetId: $targetId, message: $message) {
		successful
		result {
			id
		}
		messages {
			message
		}
	}
}
`

func deployPackage(
	ctx context.Context,
	client graphql.Client,
	organizationId string,
	targetId string,
	manifestId string,
	message string,
) (*deployPackageResponse, error) {
	req := &graphql.Request{
		OpName: "deployPackage",
		Query:  deployPackage_Operation,
		Variables: &__deployPackageInput{
			OrganizationId: organizationId,
			TargetId:       targetId,
			ManifestId:     manifestId,
			Message:        message,
		},
	}
	var err error

	var data deployPackageResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by deployPreviewEnvironment.
const deployPreviewEnvironment_Operation = `
mutation deployPreviewEnvironment ($organizationId: ID!, $projectId: ID!, $input: PreviewEnvironmentInput!) {
	deployPreviewEnvironment(projectId: $projectId, organizationId: $organizationId, input: $input) {
		successful
		result {
			id
			slug
			project {
				id
				slug
			}
		}
		messages {
			message
		}
	}
}
`

func deployPreviewEnvironment(
	ctx context.Context,
	client graphql.Client,
	organizationId string,
	projectId string,
	input PreviewEnvironmentInput,
) (*deployPreviewEnvironmentResponse, error) {
	req := &graphql.Request{
		OpName: "deployPreviewEnvironment",
		Query:  deployPreviewEnvironment_Operation,
		Variables: &__deployPreviewEnvironmentInput{
			OrganizationId: organizationId,
			ProjectId:      projectId,
			Input:          input,
		},
	}
	var err error

	var data deployPreviewEnvironmentResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by getArtifactDefinitions.
const getArtifactDefinitions_Operation = `
query getArtifactDefinitions ($organizationId: ID!) {
	artifactDefinitions(organizationId: $organizationId) {
		name
		schema
	}
}
`

func getArtifactDefinitions(
	ctx context.Context,
	client graphql.Client,
	organizationId string,
) (*getArtifactDefinitionsResponse, error) {
	req := &graphql.Request{
		OpName: "getArtifactDefinitions",
		Query:  getArtifactDefinitions_Operation,
		Variables: &__getArtifactDefinitionsInput{
			OrganizationId: organizationId,
		},
	}
	var err error

	var data getArtifactDefinitionsResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by getArtifactsByType.
const getArtifactsByType_Operation = `
query getArtifactsByType ($organizationId: ID!, $artifactType: String!) {
	artifacts(organizationId: $organizationId, input: {filter:{type:$artifactType}}) {
		next
		items {
			id
			name
		}
	}
}
`

func getArtifactsByType(
	ctx context.Context,
	client graphql.Client,
	organizationId string,
	artifactType string,
) (*getArtifactsByTypeResponse, error) {
	req := &graphql.Request{
		OpName: "getArtifactsByType",
		Query:  getArtifactsByType_Operation,
		Variables: &__getArtifactsByTypeInput{
			OrganizationId: organizationId,
			ArtifactType:   artifactType,
		},
	}
	var err error

	var data getArtifactsByTypeResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by getDeploymentById.
const getDeploymentById_Operation = `
query getDeploymentById ($organizationId: ID!, $id: ID!) {
	deployment(organizationId: $organizationId, id: $id) {
		id
		status
	}
}
`

func getDeploymentById(
	ctx context.Context,
	client graphql.Client,
	organizationId string,
	id string,
) (*getDeploymentByIdResponse, error) {
	req := &graphql.Request{
		OpName: "getDeploymentById",
		Query:  getDeploymentById_Operation,
		Variables: &__getDeploymentByIdInput{
			OrganizationId: organizationId,
			Id:             id,
		},
	}
	var err error

	var data getDeploymentByIdResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by getPackageByNamingConvention.
const getPackageByNamingConvention_Operation = `
query getPackageByNamingConvention ($organizationId: ID!, $name: String!) {
	getPackageByNamingConvention(organizationId: $organizationId, name: $name) {
		id
		namePrefix
		params
		manifest {
			id
			bundle {
				name
			}
		}
		activeDeployment {
			id
			status
		}
		environment {
			id
			slug
			project {
				id
				slug
			}
		}
	}
}
`

func getPackageByNamingConvention(
	ctx context.Context,
	client graphql.Client,
	organizationId string,
	name string,
) (*getPackageByNamingConventionResponse, error) {
	req := &graphql.Request{
		OpName: "getPackageByNamingConvention",
		Query:  getPackageByNamingConvention_Operation,
		Variables: &__getPackageByNamingConventionInput{
			OrganizationId: organizationId,
			Name:           name,
		},
	}
	var err error

	var data getPackageByNamingConventionResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by getProjectById.
const getProjectById_Operation = `
query getProjectById ($organizationId: ID!, $id: ID!) {
	project(organizationId: $organizationId, id: $id) {
		id
		name
		defaultParams
		slug
		description
	}
}
`

func getProjectById(
	ctx context.Context,
	client graphql.Client,
	organizationId string,
	id string,
) (*getProjectByIdResponse, error) {
	req := &graphql.Request{
		OpName: "getProjectById",
		Query:  getProjectById_Operation,
		Variables: &__getProjectByIdInput{
			OrganizationId: organizationId,
			Id:             id,
		},
	}
	var err error

	var data getProjectByIdResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by projects.
const projects_Operation = `
query projects ($organizationId: ID!) {
	projects(organizationId: $organizationId) {
		name
		id
		slug
		description
		defaultParams
		cost {
			monthly {
				average {
					amount
				}
			}
			daily {
				average {
					amount
				}
			}
		}
	}
}
`

func projects(
	ctx context.Context,
	client graphql.Client,
	organizationId string,
) (*projectsResponse, error) {
	req := &graphql.Request{
		OpName: "projects",
		Query:  projects_Operation,
		Variables: &__projectsInput{
			OrganizationId: organizationId,
		},
	}
	var err error

	var data projectsResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
