package bundle_test

import (
	"context"
	"os"
	"path"
	"testing"

	"github.com/massdriver-cloud/mass/internal/bundle"
	"github.com/massdriver-cloud/mass/internal/mockfilesystem"
	"sigs.k8s.io/yaml"
)

var draftNodeSchema = map[string]any{
	"schema": map[string]any{
		"properties": map[string]any{
			"foo": map[string]any{
				"properties": map[string]any{
					"infrastructure": map[string]any{
						"properties": map[string]any{
							"arn": map[string]any{
								"type": "string",
							},
						},
						"type": "object",
					},
				},
				"type": "object",
			},
		},
		"type": "object",
	},
}

var expectedTFContent = map[string][]byte{
	"_massdriver_variables.tf": []byte(`// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "draft_node_foo" {
  type = object({
    foo = optional(object({
      infrastructure = optional(object({
        arn = optional(string)
      }))
    }))
  })
}
variable "foo" {
  type = object({
    bar = number
    qux = optional(number)
  })
  default = null
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "resource_name" {
  type    = string
  default = null
}
variable "resource_type" {
  type = string
}
`),
}

// stubResolver returns a SchemaResolver that always answers with the supplied
// resource-type record. Build's dereferencer expects the nested `schema`
// shape; pass in the same fixture the old test used.
func stubResolver(rt map[string]any) bundle.SchemaResolver {
	return func(_ context.Context, _ string) (map[string]any, error) {
		return rt, nil
	}
}

func TestBuildTFVars(t *testing.T) {
	testDir := t.TempDir()
	if err := mockfilesystem.SetupBundle(testDir); err != nil {
		t.Fatal(err)
	}

	file, err := os.ReadFile(path.Join(testDir, "massdriver.yaml"))
	if err != nil {
		t.Fatal(err)
	}

	unmarshalledBundle := &bundle.Bundle{}
	if err := yaml.Unmarshal(file, unmarshalledBundle); err != nil {
		t.Fatal(err)
	}

	if err := unmarshalledBundle.Build(testDir, stubResolver(draftNodeSchema)); err != nil {
		t.Fatal(err)
	}

	for fileName, expectedContent := range expectedTFContent {
		gotContent, readFileErr := os.ReadFile(path.Join(testDir, "src", fileName))
		if readFileErr != nil {
			t.Fatal(readFileErr)
		}
		if string(gotContent) != string(expectedContent) {
			t.Errorf("Expected file content for %s to be %s but got %s", fileName, string(expectedContent), string(gotContent))
		}
	}
}
