package cmd

import (
	"bytes"
	"fmt"
	"io"
	"log"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/spf13/cobra"
	"golang.org/x/text/cases"
	"golang.org/x/text/language"
)

const mdFileEnding = ".md"

var headerTemplate = `---
id: %s
slug: %s
title: %s
sidebar_label: %s
---
`

func NewCmdDocs() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "docs",
		Short: "Generate CLI documentation",
		Long:  "Generate markdown documentation for all CLI commands",
		Run: func(cmd *cobra.Command, args []string) {
			dir, err := cmd.Flags().GetString("directory")
			if err != nil {
				log.Fatal(err)
			}
			err = os.MkdirAll(dir, os.ModePerm)
			if err != nil {
				log.Fatal(err)
			}
			err = GenMarkdownTreeCustom(rootCmd, dir, filePrepender, linkHandler)
			if err != nil {
				log.Fatal(err)
			}
		},
		Args:   cobra.NoArgs,
		Hidden: false,
		Example: `  # Generate docs to default directory
  mass docs

  # Generate to custom directory
  mass docs --directory ./documentation`,
	}

	cmd.Flags().StringP("directory", "d", "docs/generated", "directory to generate docs into")
	cmd.Flags().String("log-level", "info", "Set the log level for the server. Options are [debug, info, warn, error]")

	return cmd
}

func filePrepender(filename string) string {
	id := filepath.Base(filename)
	base := strings.TrimSuffix(id, path.Ext(id))
	slug := "/cli/commands/" + strings.ToLower(base)
	title := cases.Title(language.AmericanEnglish).String(strings.ReplaceAll(base, "_", " "))

	return fmt.Sprintf(headerTemplate, id, slug, title, title)
}

func linkHandler(filename string) string {
	base := strings.TrimSuffix(filename, path.Ext(filename))
	return "/cli/commands/" + base
}

// Currently cobra has a bug where there is an extra line added to the end of the md file when
// the DisableAutoGenTag = true and this causes pre-commit to have to edit the file after generation
// so the below section is copied from https://github.com/spf13/cobra/blob/v1.7.0/doc/md_docs.go#L55
// with a fix to move the newline being added before the timestamp
// https://github.com/spf13/cobra/issues/2029

// GenMarkdownTreeCustom is the the same as GenMarkdownTree, but
// with custom filePrepender and linkHandler.
func GenMarkdownTreeCustom(cmd *cobra.Command, dir string, filePrepender, linkHandler func(string) string) error {
	for _, c := range cmd.Commands() {
		if !c.IsAvailableCommand() || c.IsAdditionalHelpTopicCommand() {
			continue
		}
		if err := GenMarkdownTreeCustom(c, dir, filePrepender, linkHandler); err != nil {
			return err
		}
	}

	basename := strings.ReplaceAll(cmd.CommandPath(), " ", "_") + mdFileEnding
	filename := filepath.Join(dir, basename)
	f, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer f.Close()

	if _, err = io.WriteString(f, filePrepender(filename)); err != nil {
		return err
	}

	return GenMarkdownCustom(cmd, f, linkHandler)
}

// GenMarkdownCustom creates custom markdown output.
func GenMarkdownCustom(cmd *cobra.Command, w io.Writer, linkHandler func(string) string) error {
	cmd.InitDefaultHelpCmd()
	cmd.InitDefaultHelpFlag()

	buf := new(bytes.Buffer)
	name := cmd.CommandPath()

	buf.WriteString("## " + name + "\n\n")
	buf.WriteString(cmd.Short + "\n\n")
	if len(cmd.Long) > 0 {
		buf.WriteString("### Synopsis\n\n")
		buf.WriteString(cmd.Long + "\n\n")
	}

	if cmd.Runnable() {
		buf.WriteString(fmt.Sprintf("```\n%s\n```\n\n", cmd.UseLine()))
	}

	if len(cmd.Example) > 0 {
		buf.WriteString("### Examples\n\n")
		buf.WriteString(fmt.Sprintf("```\n%s\n```\n\n", cmd.Example))
	}

	if err := printOptions(buf, cmd, name); err != nil {
		return err
	}
	if hasSeeAlso(cmd) {
		buf.WriteString("### SEE ALSO\n\n")
		if cmd.HasParent() {
			parent := cmd.Parent()
			pname := parent.CommandPath()
			link := pname + mdFileEnding
			link = strings.ReplaceAll(link, " ", "_")
			buf.WriteString(fmt.Sprintf("* [%s](%s)\t - %s\n", pname, linkHandler(link), parent.Short))
			cmd.VisitParents(func(c *cobra.Command) {
				if c.DisableAutoGenTag {
					cmd.DisableAutoGenTag = c.DisableAutoGenTag
				}
			})
		}

		children := cmd.Commands()
		sort.Sort(byName(children))

		for _, child := range children {
			if !child.IsAvailableCommand() || child.IsAdditionalHelpTopicCommand() {
				continue
			}
			cname := name + " " + child.Name()
			link := cname + mdFileEnding
			link = strings.ReplaceAll(link, " ", "_")
			buf.WriteString(fmt.Sprintf("* [%s](%s)\t - %s\n", cname, linkHandler(link), child.Short))
		}
	}
	if !cmd.DisableAutoGenTag {
		// This line was moved from inside the end of the hasSeeAlso block which stops it from adding
		// an extra newline
		buf.WriteString("\n")
		buf.WriteString("###### Auto generated by spf13/cobra on " + time.Now().Format("2-Jan-2006") + "\n")
	}
	_, err := buf.WriteTo(w)
	return err
}

// Test to see if we have a reason to print See Also information in docs
// Basically this is a test for a parent command or a subcommand which is
// both not deprecated and not the autogenerated help command.
func hasSeeAlso(cmd *cobra.Command) bool {
	if cmd.HasParent() {
		return true
	}
	for _, c := range cmd.Commands() {
		if !c.IsAvailableCommand() || c.IsAdditionalHelpTopicCommand() {
			continue
		}
		return true
	}
	return false
}

func printOptions(buf *bytes.Buffer, cmd *cobra.Command, _ string) error {
	flags := cmd.NonInheritedFlags()
	flags.SetOutput(buf)
	if flags.HasAvailableFlags() {
		buf.WriteString("### Options\n\n```\n")
		flags.PrintDefaults()
		buf.WriteString("```\n\n")
	}

	parentFlags := cmd.InheritedFlags()
	parentFlags.SetOutput(buf)
	if parentFlags.HasAvailableFlags() {
		buf.WriteString("### Options inherited from parent commands\n\n```\n")
		parentFlags.PrintDefaults()
		buf.WriteString("```\n\n")
	}
	return nil
}

type byName []*cobra.Command

func (s byName) Len() int           { return len(s) }
func (s byName) Swap(i, j int)      { s[i], s[j] = s[j], s[i] }
func (s byName) Less(i, j int) bool { return s[i].Name() < s[j].Name() }
