package provisioners_test

import (
	"errors"
	"os"
	"path"
	"reflect"
	"slices"
	"strings"
	"testing"

	"github.com/massdriver-cloud/mass/pkg/provisioners"
)

const autoGeneratedHeader = "// This file is auto-generated by massdriver from your massdriver.yaml file.\n// Any changes made directly to this file will be overwritten on the next build.\n// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).\n"

func TestOpentofuExportMassdriverInputs(t *testing.T) {
	type test struct {
		name                   string
		tfFile                 string // testdata fixture to use as variables.tf; defaults to tc.name
		variables              map[string]any
		existingMassdriverVars string // pre-populate _massdriver_variables.tf with this content
		want                   string
		errString              string
	}
	tests := []test{
		{
			name: "same",
			variables: map[string]any{
				"required": []any{"bar", "foo"},
				"properties": map[string]any{
					"bar": map[string]any{
						"type": "string",
					},
					"foo": map[string]any{
						"type": "string",
					},
				},
			},
			want: ``,
		},
		{
			name: "missingopentofu",
			variables: map[string]any{
				"required": []any{"bar", "foo"},
				"properties": map[string]any{
					"bar": map[string]any{
						"type": "string",
					},
					"foo": map[string]any{
						"type": "string",
					},
				},
			},
			want: autoGeneratedHeader + `variable "bar" {
  type = string
}
`,
		},
		{
			name:   "regenerate",
			tfFile: "missingopentofu",
			variables: map[string]any{
				"required": []any{"bar", "foo"},
				"properties": map[string]any{
					"bar": map[string]any{
						"type": "string",
					},
					"foo": map[string]any{
						"type": "string",
					},
				},
			},
			existingMassdriverVars: autoGeneratedHeader + `variable "bar" {
  type = string
}
`,
			want: autoGeneratedHeader + `variable "bar" {
  type = string
}
`,
		},
		{
			name:   "regenerateclean",
			tfFile: "same",
			variables: map[string]any{
				"required": []any{"bar", "foo"},
				"properties": map[string]any{
					"bar": map[string]any{
						"type": "string",
					},
					"foo": map[string]any{
						"type": "string",
					},
				},
			},
			existingMassdriverVars: autoGeneratedHeader + `variable "bar" {
  type = string
}
`,
			want: ``,
		},
		{
			name: "missingmassdriver",
			variables: map[string]any{
				"required": []any{"foo"},
				"properties": map[string]any{
					"foo": map[string]any{
						"type": "string",
					},
				},
			},
			want: ``,
		},
		{
			name:      "invalid",
			errString: "failed to read existing OpenTofu variable declarations",
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			testDir := t.TempDir()

			tfFile := tc.tfFile
			if tfFile == "" {
				tfFile = tc.name
			}

			content, err := os.ReadFile(path.Join("testdata", "opentofu", tfFile+".tf"))
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}

			err = os.WriteFile(path.Join(testDir, "variables.tf"), content, 0644)
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}

			if tc.existingMassdriverVars != "" {
				err = os.WriteFile(path.Join(testDir, "_massdriver_variables.tf"), []byte(tc.existingMassdriverVars), 0644)
				if err != nil {
					t.Fatalf("unexpected error writing existing massdriver vars: %v", err)
				}
			}

			prov := provisioners.OpentofuProvisioner{}
			err = prov.ExportMassdriverInputs(testDir, tc.variables)
			if tc.errString == "" && err != nil {
				t.Errorf("Unexpected error during validation: %s", err)
			}
			if tc.errString != "" {
				if err == nil {
					t.Fatalf("Expected error but got none")
				}
				if !strings.Contains(err.Error(), tc.errString) {
					t.Fatalf("got error %s want %s", err.Error(), tc.errString)
				}
			}

			expectedFilepath := path.Join(testDir, "_massdriver_variables.tf")
			if len(tc.want) > 0 {
				got, readErr := os.ReadFile(expectedFilepath)
				if readErr != nil {
					t.Fatalf("%d, unexpected error", readErr)
				}

				if string(got) != tc.want {
					t.Errorf("got %s want %s", got, tc.want)
				}
			} else {
				if _, statErr := os.Stat(expectedFilepath); !errors.Is(statErr, os.ErrNotExist) {
					t.Fatalf("file exists when it shouldn't")
				}
			}
		})
	}
}

func TestOpentofuReadProvisionerInputs(t *testing.T) {
	type test struct {
		name string
		want map[string]any
	}
	tests := []test{
		{
			name: "same",
			want: map[string]any{
				"required": []any{"bar", "foo"},
				"properties": map[string]any{
					"bar": map[string]any{
						"title": "bar",
						"type":  "string",
					},
					"foo": map[string]any{
						"title": "foo",
						"type":  "string",
					},
				},
			},
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			testDir := t.TempDir()

			content, err := os.ReadFile(path.Join("testdata", "opentofu", tc.name+".tf"))
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}

			err = os.WriteFile(path.Join(testDir, "variables.tf"), content, 0644)
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}

			prov := provisioners.OpentofuProvisioner{}
			got, err := prov.ReadProvisionerInputs(testDir)
			if err != nil {
				t.Errorf("Error during validation: %s", err)
			}

			if !reflect.DeepEqual(got, tc.want) {
				t.Errorf("want %v got %v", got, tc.want)
			}
		})
	}
}

func TestOpentofuInitializeStep(t *testing.T) {
	type test struct {
		name       string
		modulePath string
		want       []string
	}
	tests := []test{
		{
			name:       "same",
			modulePath: "testdata/opentofu/initializetest",
			want: []string{
				"foo.tf",
				".terraform.lock.hcl",
			},
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			testDir := t.TempDir()

			_, createErr := os.Create(path.Join(testDir, "main.tf"))
			if createErr != nil {
				t.Fatalf("unexpected error: %s", createErr)
				return
			}

			prov := provisioners.OpentofuProvisioner{}
			initErr := prov.InitializeStep(testDir, tc.modulePath)
			if initErr != nil {
				t.Fatalf("unexpected error: %s", initErr)
			}

			got, gotErr := os.ReadDir(testDir)
			if gotErr != nil {
				t.Fatalf("unexpected error: %s", gotErr)
			}

			if len(got) != len(tc.want) {
				t.Errorf("want %v got %v", got, tc.want)
			}
			for _, curr := range got {
				if !slices.Contains(tc.want, curr.Name()) {
					t.Errorf("%v doesn't exist in %v", curr.Name(), tc.want)
				}
			}
		})
	}
}
