package provisioners

import (
	"bytes"
	"encoding/json"
	"errors"
	"os"
	"path"

	"github.com/massdriver-cloud/airlock/pkg/opentofu"
)

// OpentofuProvisioner implements Provisioner for OpenTofu/Terraform modules.
type OpentofuProvisioner struct{}

// ExportMassdriverInputs generates the _massdriver_variables.tf file from the massdriver schema.
func (p *OpentofuProvisioner) ExportMassdriverInputs(stepPath string, variables map[string]any) (retErr error) {
	massdriverVarsFile := path.Join(stepPath, "_massdriver_variables.tf")
	massdriverVarsBackup := massdriverVarsFile + ".bak"

	// If _massdriver_variables.tf already exists, rename it so airlock won't read it
	// during the scan. This allows variables declared there to be regenerated.
	// The defer below restores the backup on any error, or removes it on success.
	if _, statErr := os.Stat(massdriverVarsFile); statErr == nil {
		if renameErr := os.Rename(massdriverVarsFile, massdriverVarsBackup); renameErr != nil {
			return renameErr
		}
		defer func() {
			if retErr != nil {
				_ = os.Remove(massdriverVarsFile)                       // best-effort cleanup; error not actionable in defer
				_ = os.Rename(massdriverVarsBackup, massdriverVarsFile) // best-effort cleanup; error not actionable in defer
			} else {
				_ = os.Remove(massdriverVarsBackup) // best-effort cleanup; error not actionable in defer
			}
		}()
	} else if !errors.Is(statErr, os.ErrNotExist) {
		return statErr
	}

	// read existing OpenTofu variables for this step (excludes _massdriver_variables.tf)
	tofuVarsImport := opentofu.TofuToSchema(stepPath)
	if tofuVarsImport.Schema == nil {
		return errors.New("failed to read existing OpenTofu variable declarations: " + tofuVarsImport.PrettyDiags())
	}

	newVariables := FindMissingFromAirlock(variables, tofuVarsImport.Schema)
	newVariablesProps, newVariablesPropsOk := newVariables["properties"].(map[string]any)
	if !newVariablesPropsOk {
		return errors.New("failed to get properties from missing variables")
	}
	if len(newVariablesProps) == 0 {
		return nil
	}

	schemaBytes, marshallErr := json.Marshal(newVariables)
	if marshallErr != nil {
		return marshallErr
	}

	content, transpileErr := opentofu.SchemaToTofu(bytes.NewReader(schemaBytes))
	if transpileErr != nil {
		return transpileErr
	}

	header := []byte("// This file is auto-generated by massdriver from your massdriver.yaml file.\n// Any changes made directly to this file will be overwritten on the next build.\n// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).\n")
	content = append(header, content...)

	if writeErr := os.WriteFile(massdriverVarsFile, content, 0600); writeErr != nil {
		return writeErr
	}

	return nil
}

// ReadProvisionerInputs reads all OpenTofu variable declarations from the step directory.
func (p *OpentofuProvisioner) ReadProvisionerInputs(stepPath string) (map[string]any, error) {
	tofuVarsImport := opentofu.TofuToSchema(stepPath)

	schemaBytes, marshallErr := json.Marshal(tofuVarsImport.Schema)
	if marshallErr != nil {
		return nil, marshallErr
	}

	variables := map[string]any{}
	unmarshalErr := json.Unmarshal(schemaBytes, &variables)
	if unmarshalErr != nil {
		return nil, unmarshalErr
	}

	return variables, nil
}

// InitializeStep copies the OpenTofu module directory into the step directory, excluding state files.
func (p *OpentofuProvisioner) InitializeStep(stepPath string, sourcePath string) error {
	pathInfo, statErr := os.Stat(sourcePath)
	if statErr != nil {
		return statErr
	}
	if !pathInfo.IsDir() {
		return errors.New("path is not a directory, cannot initialize")
	}

	// remove the dummy main.tf if we are copying from a source
	maintfPath := path.Join(stepPath, "main.tf")
	if _, maintfErr := os.Stat(maintfPath); maintfErr == nil {
		err := os.Remove(maintfPath)
		if err != nil {
			return err
		}
	}

	// intentionally not ignoring the .terraform.lock.hcl file since it should be copied
	ignorePatterns := []string{
		".terraform",
		"*.tfstate",
		"*.tfstate.backup",
		"*.tfvars",
		"*.tfvars.json",
	}
	return copyDir(sourcePath, stepPath, ignorePatterns)
}
